# datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.111.6:3306/ssm_db?serverTimezone=UTC
    username: yaoxi
    password: yaoxi
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1 # redis的主机ip
    port: 6379
#  boot:
#    admin:
#      client:
#        url: http://localhost:8088

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.yx: debug
    org.springframework: info



