# datasource
spring:
  datasource:
    username: yaoxi
    password: yaoxi
    url: jdbc:mysql://192.168.31.6:3306/ssm_db
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
