# datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.111.6:3306/ssm_db?serverTimezone=UTC
    username: yaoxi
    password: yaoxi
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1 # redis的主机ip
    port: 6379
  elasticsearch:
    rest:
      uris: 192.168.111.134:9200
#  boot:
#    admin:
#      client:
#        url: http://localhost:8088

# 监控相关
management:
  # 监控健康详细信息
  endpoint:
    health:
      show-details: always
  # 监控所有的endpoints
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.yx: debug
    org.springframework: info


